### PR TITLE
Freeing the commands and the command chain created during dispatch

### PR DESCRIPTION
**Pull request by eddierichter-amd**

### CODE REVIEW

**Comment by makslevental** [comment]
I can't comment since it isn't a touched line but don't you need to free the `cmd`s themselves too? 

https://github.com/nod-ai/ROCR-Runtime/blob/54b07d981c9dc4a6675c4bee9107f7b2ab3912bd/runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp#L378

also in this file is the `ring_buf_` which is allocated but never freed (like in [AqlQueue](https://github.com/nod-ai/ROCR-Runtime/blob/54b07d981c9dc4a6675c4bee9107f7b2ab3912bd/runtime/hsa-runtime/core/runtime/amd_aql_queue.cpp#L760))

https://github.com/nod-ai/ROCR-Runtime/blob/54b07d981c9dc4a6675c4bee9107f7b2ab3912bd/runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp#L104

**Comment by eddierichter-amd** [comment]
> I can't comment since it isn't a touched line but don't you need to free the `cmd`s themselves too?
> 
> https://github.com/nod-ai/ROCR-Runtime/blob/54b07d981c9dc4a6675c4bee9107f7b2ab3912bd/runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp#L378
> 
> also in this file is the `ring_buf_` which is allocated but never freed (like in [AqlQueue](https://github.com/nod-ai/ROCR-Runtime/blob/54b07d981c9dc4a6675c4bee9107f7b2ab3912bd/runtime/hsa-runtime/core/runtime/amd_aql_queue.cpp#L760))
> 
> https://github.com/nod-ai/ROCR-Runtime/blob/54b07d981c9dc4a6675c4bee9107f7b2ab3912bd/runtime/hsa-runtime/core/runtime/amd_aie_aql_queue.cpp#L104

We go through all of the cmd_handles and free all of them here: https://github.com/nod-ai/ROCR-Runtime/pull/29/files#diff-d794c4f5b69c550f71f08837a96b68bb2dad1cd8750f1c41623a92d4dcef9a7eR444-R447. Are there some commands that we are missing? Good point on the queue will add that to this PR as well.

**Comment by makslevental** [comment]
sorry I should've been more specific - shouldn't the buffers themselves be `munmap`ed? Like I did here in the other PR https://github.com/nod-ai/ROCR-Runtime/pull/28/files#diff-d794c4f5b69c550f71f08837a96b68bb2dad1cd8750f1c41623a92d4dcef9a7e

**Comment by eddierichter-amd** [comment]
> sorry I should've been more specific - shouldn't the buffers themselves be `munmap`ed? Like I did here in the other PR https://github.com/nod-ai/ROCR-Runtime/pull/28/files#diff-d794c4f5b69c550f71f08837a96b68bb2dad1cd8750f1c41623a92d4dcef9a7e

Wow you are good! Didn't realize you had a PR that had this :). Alright I am both unmapping and closing as that is consistent with how the XRT shim is dealing with cmds (unmapping: https://github.com/amd/xdna-driver/blob/867e2f9f5f21596ec642e9ca5321de7a0863c14d/src/shim/bo.cpp#L59-L62 and closing: https://github.com/amd/xdna-driver/blob/867e2f9f5f21596ec642e9ca5321de7a0863c14d/src/shim/bo.cpp#L23-L27) if we learn that this is redundant happy to remove closing or unmapping. Also added the queue ring buf deallocation via the system deallocator.

**Review by makslevental — APPROVED** [review]
LGTM - in my local testing of basically the same changes this made most (all?) of the kernel leaks go away.

**Pull request merged**
